version: "3.9"

services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    env_file:  
    - ./reviews/.env
    depends_on:
      - redis
    command: python manage.py runserver

  worker:
    container_name: worker
    build: .
    depends_on:
      - redis
      - web
    command: celery -A crm_project.celery worker -l info

  beat:
    container_name: beat
    build: .
    depends_on:
      - redis
      - worker
    command: celery -A crm_project.celery beat -l info # --scheduler django_celery_beat.schedulers:DatabaseScheduler

  redis:
    container_name: redis
    image: redis:latest
    ports:  
      - "6379:6379"
    volumes:  
    - ./redis-data:/data