version: "3.9"

services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    env_file:  
    - ./reviews/.env
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    container_name: worker
    build: .
    depends_on:
      - redis
      - web
    command: celery -A crm_project.celery worker -l info

  beat:
    container_name: beat
    build: .
    depends_on:
      - redis
      - worker
    command: celery -A crm_project.celery beat -l info # --scheduler django_celery_beat.schedulers:DatabaseScheduler

  redis:
    container_name: redis
    image: redis:latest
    ports:  
      - "6379:6379"
    volumes:  
    - ./redis-data:/data

  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=crm_project
      - POSTGRES_USER=maks
      - POSTGRES_PASSWORD=maks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}