version: "3.9"

services:
  web:
    container_name: web
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8000:8000"
    env_file:  
    - .env
    depends_on:
      - db
      - redis
      # - selenium
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    container_name: worker
    build: .
    depends_on:
      - redis
      - web
    command: celery -A crm_project.celery worker -l info

  beat:
    container_name: beat
    build: .
    depends_on:
      - redis
      - worker
    command: celery -A crm_project.celery beat -l info # --scheduler django_celery_beat.schedulers:DatabaseScheduler

  redis:
    container_name: redis
    image: redis:latest
    ports:  
      - "6379:6379"
    volumes:  
    - ./redis-data:/data

  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=crm_project
      - POSTGRES_USER=maks
      - POSTGRES_PASSWORD=maks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # selenium:
  #   image: selenium/standalone-chromium:latest
  #   container_name: selenium-container
  #   restart: unless-stopped
  #   shm_size: 2g
  #   ports:
  #     - "4444:4444"  # Selenium WebDriver API
  #     - "7900:7900"  # VNC Viewer
  #   environment:
  #     - SE_NODE_MAX_SESSIONS=1
  #     - SE_NODE_OVERRIDE_MAX_SESSIONS=true
  #     - SE_NODE_SESSION_TIMEOUT=300
  #     - SE_NODE_GRID_URL=http://selenium:4444/wd/hub
  #     - SE_NODE_DETECT_DRIVERS=false

volumes:
  postgres_data: {}